name: locosopa
description: Low-code software homepages

inputs:
  config:
    description: Path to config file
    required: true
  path:
    description: Path to deploy to
    default: locosopa_action
  deploy:
    description: Boolean whether locosopa shall be deployed to github pages
    default: "true"
outputs:
  page-url:
    description: page url
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: "koesterlab/locosopa"
        path: ${{ inputs.path }}
        ref: ${{ env.ACTION_REF }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        miniforge-version: latest
        activate-environment: locosopa-env
        environment-file: ${{ inputs.path }}/locosopa/environment.yml

    - name: Build page
      shell: bash -el {0}
      run: |
        cd ${{ inputs.path }}/locosopa && snakemake -c1 --software-deployment-method conda --config page_config=${{ github.workspace }}/${{ inputs.config }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ inputs.path }}/locosopa/build

    - name: Setup Pages
      if: ${{ inputs.deploy == 'true' }}
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      if: ${{ inputs.deploy == 'true' }}
      id: deployment
      uses: actions/deploy-pages@v2

