from pathlib import Path

asset_base = Path(config['asset_base'])

assets = config["assets"].split(",")


rule all:
    input:
        # TODO add print_landscape once fixed
        expand(["build/{page}.html", "build/{page}.css"], page=["index"]),
        expand("build/{asset}", asset=assets),


rule build_css:
    input:
        "build/{page}.html",
        css="src/style.css",
    output:
        "build/{page}.css",
    conda:
        "envs/nodejs.yaml"
    shell:
        "npm install; npx tailwindcss -i {input.css} -o {output}"


rule build_html:
    input:
        config=config["page_config"],
    output:
        "build/{page}.html",
    conda:
        "envs/ytml.yaml"
    shell:
        "ytml src build {input.config} {wildcards.page}.ytml.yaml"


rule copy_asset:
    input:
        f"{asset_base}/{{asset}}",
    output:
        "build/{asset}",
    shell:
        "mkdir -p $(dirname {output}); "
        "cp {input} {output}"
