from pathlib import Path

asset_base = Path(config['asset_base'])

assets = config["assets"].split(",")


rule all:
    input:
        "build/index.html",
        "build/style.css",
        [
            f"build/{asset}"
            for asset in assets
        ]


rule build_css:
    input:
        "build/index.html",
        css="src/style.css",
    output:
        "build/style.css",
    conda:
        "envs/nodejs.yaml"
    shell:
        "npm install; npx tailwindcss -i {input.css} -o {output}"


rule build_html:
    input:
        config=config["page_config"],
    output:
        "build/index.html",
    conda:
        "envs/ytml.yaml"
    shell:
        "ytml src build {input.config} index.ytml.yaml"


rule copy_asset:
    input:
        f"{asset_base}/{{asset}}",
    output:
        "build/{asset}",
    shell:
        "mkdir -p $(dirname {output}); "
        "cp {input} {output}"
